Changes made to Makefile.template in Dino

diff --git a/Makefile.template b/Makefile.template
--- a/Makefile.template
+++ b/Makefile.template
@@ -15,6 +15,7 @@ mandir = $(datadir)/man
 LV2PEG = lv2peg
 
 # Don't modify any variables below this line
+SHELL := /bin/bash
 UNAME = $(shell uname)
 
 
@@ -400,57 +401,52 @@ check-pkg-deps:
 
 
 # TEST REPORT GENERATION
+# We want a report of the clean test builds as well, so tests are built
+# and run in a separate dist directory.
 KERNEL_NAME := $(shell uname -s | sed 's/"/\\"/g')
 KERNEL_RELEASE := $(shell uname -r | sed 's/"/\\"/g')
 MACHINE := $(shell uname -m | sed 's/"/\\"/g')
 OPERATING_SYSTEM := $(shell uname -o | sed 's/"/\\"/g')
 UNIQUE_TOKEN := $(shell for i in 1 2 3 4; do printf '%04x' $$RANDOM; done)
-TESTREPORT := $(PACKAGE_NAME)-$(PACKAGE_VERSION)-test-$(UNIQUE_TOKEN).xml
+TESTREPORT := $(PACKAGE_NAME)-$(PACKAGE_VERSION)-test-$(UNIQUE_TOKEN)
 
-test-report: $(TESTS)
-	rm -f $(TESTREPORT).bz2
-	echo "<testroot package=\"$(PACKAGE_NAME)\" version=\"$(PACKAGE_VERSION)\" unique_token=\"$(UNIQUE_TOKEN)\">" > $(TESTREPORT)
-	echo >> $(TESTREPORT)
-	echo "  <environment kernel=\"$(KERNEL_NAME)\" kernel_release=\"$(KERNEL_RELEASE)\" machine=\"$(MACHINE)\" operating_system=\"$(OPERATING_SYSTEM)\" c_compiler=\"$(shell $(CC) --version | head -n 1)\" cxx_compiler=\"$(shell $(CXX) --version | head -n 1)\" />" >> $(TESTREPORT)
-	echo >> $(TESTREPORT)
-	$(foreach pkgname, $(PKG_NAMES), echo "  <dependency name=\"$(pkgname)\" version=\""`pkg-config --modversion $(pkgname)`"\" />" >> $(TESTREPORT);)
-	echo >> $(TESTREPORT)
-	export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}$(LIBRARY_DIRS); \
+test-report:
+	rm -rf $(TESTREPORT)
+	rm -rf tmp-test-dist
+	$(MAKE) DIST_NAME=tmp-test-dist dist-dir
+	cp Makefile.config tmp-test-dist
+	@echo " + Compiling tests..."
+	@cd tmp-test-dist; $(MAKE) -k all-tests > build.stdout 2> >(tee build.stderr >&2); status=$$?; echo $$status > build.status; if [ $$status != 0 ]; then echo " *** Failed to compile some tests, will continue anyway."; else echo " + Done compiling."; fi
+	@echo " + Running tests..."
+	@cd tmp-test-dist; $(MAKE) UNIQUE_TOKEN=$(UNIQUE_TOKEN) internal-test-report
+	@echo " + Done testing."
+	cd tmp-test-dist; cp build.stdout build.stderr build.status $(TESTREPORT)
+	mv tmp-test-dist/$(TESTREPORT) $(TESTREPORT)
+	tar cj $(TESTREPORT) > $(TESTREPORT).tar.bz2
+	rm -rf tmp-test-dist
+	rm -rf $(TESTREPORT)
+
+all-tests: $(TESTS)
+
+internal-test-report:
+	@rm -f $(TESTREPORT)
+	@mkdir $(TESTREPORT)
+	@echo "package = \"$(PACKAGE_NAME)\"" > $(TESTREPORT)/info
+	@echo "version = \"$(PACKAGE_VERSION)\"" >> $(TESTREPORT)/info
+	@echo "unique_token = \"$(UNIQUE_TOKEN)\"" >> $(TESTREPORT)/info
+	@echo >> $(TESTREPORT)/info
+	@echo "kernel = \"$(KERNEL_NAME)\"" >> $(TESTREPORT)/info
+	@echo "kernel_release = \"$(KERNEL_RELEASE)\"" >> $(TESTREPORT)/info
+	@echo "machine = \"$(MACHINE)\"" >> $(TESTREPORT)/info
+	@echo "operating_system = \"$(OPERATING_SYSTEM)\"" >> $(TESTREPORT)/info
+	@echo "c_compiler = \"$(shell $(CC) --version | head -n 1)\"" >> $(TESTREPORT)/info
+	@echo "cxx_compiler = \"$(shell $(CXX) --version | head -n 1)\"" >> $(TESTREPORT)/info
+	@echo >> $(TESTREPORT)/info
+	@$(foreach pkgname, $(PKG_NAMES), echo "dependency.$(pkgname) = \""`pkg-config --modversion $(pkgname)`"\"" >> $(TESTREPORT)/info;)
+	export LD_LIBRARY_PATH=$${LD_LIBRARY_PATH}$(LIBRARY_DIRS); \
 	for test in $(TESTS); do \
-	  ./$$test $(TESTFLAGS) > test.stdout.tmp 2> test.stderr.tmp; \
+	  mkdir -p $(TESTREPORT)/$$test; \
+	  ./$$test $(TESTFLAGS) > $(TESTREPORT)/$$test/stdout 2> $(TESTREPORT)/$$test/stderr; \
 	  status=$$?; \
-	  echo "  <test program=\"$$test\" exit_status=\"$$status\" >" >> $(TESTREPORT); \
-	  echo "    <stderr>" >> $(TESTREPORT); \
-	  echo -n "      <![CDATA[" >> $(TESTREPORT); \
-	  cat test.stderr.tmp | sed 's/]]>/]]]]><![CDATA[>/g' >> $(TESTREPORT); \
-	  echo "]]>" >> $(TESTREPORT); \
-	  echo "    </stderr>" >> $(TESTREPORT); \
-	  echo "    <stdout>" >> $(TESTREPORT); \
-	  echo -n "      <![CDATA[" >> $(TESTREPORT); \
-	  cat test.stdout.tmp | sed 's/]]>/]]]]><![CDATA[>/g' >> $(TESTREPORT); \
-	  echo "]]>" >> $(TESTREPORT); \
-	  echo "    </stdout>" >> $(TESTREPORT); \
-	  echo "  </test>" >> $(TESTREPORT); \
-	  rm -f test.stderr.tmp test.stdout.tmp; \
+	  echo $$status > $(TESTREPORT)/$$test/exit_status; \
 	done
-	echo >> $(TESTREPORT)
-	echo "</testroot>" >> $(TESTREPORT)
-	bzip2 $(TESTREPORT)
-
-
-# RELEASE ANNOUNCEMENT
-export PACKAGE_DESCRIPTION
-release-mail:
-	@echo "$(PACKAGE_DISPLAY_NAME) $(PACKAGE_VERSION) has been released."
-	@echo ""
-	@echo "$$PACKAGE_DESCRIPTION"
-	@echo ""
-	@echo "Changes:"
-	@end=`grep -n -m 1 '^$$' ChangeLog | sed 's/:.*//'`; head -n $$(($$end - 1)) ChangeLog | tail -n +2 | sed 's/\t/ /g'
-	@echo ""
-	@echo "Tarball:"
-	@echo "GPG signature file:"
-	@echo ""
-	@echo "Webpage: $(PACKAGE_WEBPAGE)"
-	@echo "Bug tracker: $(PACKAGE_BUGTRACKER)"
-	@echo "Version control: $(PACKAGE_VC)"
